# =============================================================
# models.py — CyberQuest Database Models
# Author: Prashan Manandhar (CIHE241182)
# Description: SQLAlchemy ORM models for all database tables
# =============================================================

from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()


# -------------------------------------------------------------
# User Model
# Stores all registered users (students and teachers)
# -------------------------------------------------------------
class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id             = db.Column(db.Integer, primary_key=True)
    username       = db.Column(db.String(80), unique=True, nullable=False)
    email          = db.Column(db.String(120), unique=True, nullable=False)
    password_hash  = db.Column(db.String(255), nullable=False)

    # Role: 'student' or 'teacher'
    role           = db.Column(db.String(20), nullable=False, default='student')

    # 2FA secret key generated by PyOTP
    totp_secret    = db.Column(db.String(32), nullable=True)

    # Tracks consecutive failed login attempts
    login_attempts = db.Column(db.Integer, default=0)

    created_at     = db.Column(db.DateTime, default=datetime.utcnow)

    # Relationships
    scores         = db.relationship('Score', backref='user', lazy=True)
    badges         = db.relationship('UserBadge', backref='user', lazy=True)
    login_logs     = db.relationship('LoginAttempt', backref='user', lazy=True)

    def __repr__(self):
        return f'<User {self.username} ({self.role})>'

    def is_teacher(self):
        """Returns True if user has teacher role."""
        return self.role == 'teacher'

    def is_student(self):
        """Returns True if user has student role."""
        return self.role == 'student'

    def has_2fa_enabled(self):
        """Returns True if user has set up 2FA."""
        return self.totp_secret is not None


# -------------------------------------------------------------
# Challenge Model
# Stores all quiz questions across 3 categories
# -------------------------------------------------------------
class Challenge(db.Model):
    __tablename__ = 'challenges'

    id             = db.Column(db.Integer, primary_key=True)

    # Category: 'phishing', 'password', 'safe_browsing'
    category       = db.Column(db.String(50), nullable=False)

    question       = db.Column(db.Text, nullable=False)
    option_a       = db.Column(db.String(255), nullable=False)
    option_b       = db.Column(db.String(255), nullable=False)
    option_c       = db.Column(db.String(255), nullable=False)
    option_d       = db.Column(db.String(255), nullable=False)

    # Correct answer: 'a', 'b', 'c', or 'd'
    correct_answer = db.Column(db.String(1), nullable=False)

    # Difficulty: 'easy', 'medium', 'hard'
    difficulty     = db.Column(db.String(10), nullable=False, default='easy')

    # Points awarded for correct answer
    points         = db.Column(db.Integer, nullable=False, default=10)

    # Relationships
    scores         = db.relationship('Score', backref='challenge', lazy=True)

    def __repr__(self):
        return f'<Challenge [{self.category}] {self.question[:40]}...>'


# -------------------------------------------------------------
# Score Model
# Records every answer a student submits
# -------------------------------------------------------------
class Score(db.Model):
    __tablename__ = 'scores'

    id           = db.Column(db.Integer, primary_key=True)
    user_id      = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    challenge_id = db.Column(db.Integer, db.ForeignKey('challenges.id'), nullable=False)

    # Whether the student answered correctly
    is_correct   = db.Column(db.Boolean, nullable=False)

    # The answer the student selected ('a', 'b', 'c', or 'd')
    selected     = db.Column(db.String(1), nullable=True)

    answered_at  = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<Score user={self.user_id} challenge={self.challenge_id} correct={self.is_correct}>'


# -------------------------------------------------------------
# Badge Model
# Defines all available badges in the system
# -------------------------------------------------------------
class Badge(db.Model):
    __tablename__ = 'badges'

    id          = db.Column(db.Integer, primary_key=True)
    name        = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    # Criteria description (used for display only)
    criteria    = db.Column(db.String(255), nullable=False)

    # Icon name from Bootstrap Icons (e.g. 'shield-check')
    icon        = db.Column(db.String(50), default='award')

    # Relationships
    user_badges = db.relationship('UserBadge', backref='badge', lazy=True)

    def __repr__(self):
        return f'<Badge {self.name}>'


# -------------------------------------------------------------
# UserBadge Model
# Junction table — records which badges each user has earned
# -------------------------------------------------------------
class UserBadge(db.Model):
    __tablename__ = 'user_badges'

    id        = db.Column(db.Integer, primary_key=True)
    user_id   = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    badge_id  = db.Column(db.Integer, db.ForeignKey('badges.id'), nullable=False)
    earned_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f'<UserBadge user={self.user_id} badge={self.badge_id}>'


# -------------------------------------------------------------
# LoginAttempt Model
# Security log — records every login attempt (success or fail)
# Used to detect brute force attacks
# -------------------------------------------------------------
class LoginAttempt(db.Model):
    __tablename__ = 'login_attempts'

    id         = db.Column(db.Integer, primary_key=True)
    user_id    = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)

    # IP address of the request
    ip_address = db.Column(db.String(45), nullable=True)

    # True = successful login, False = failed login
    success    = db.Column(db.Boolean, nullable=False)

    timestamp  = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        status = 'SUCCESS' if self.success else 'FAILED'
        return f'<LoginAttempt user={self.user_id} {status} @ {self.timestamp}>'